const API='http://localhost:8080';
const state={farmer:null,officer:null,farmers:[],officers:[],regions:[],tickets:[],activeTicket:null};
const $=id=>document.getElementById(id);
async function api(path,opt={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const txt=await r.text();let d;try{d=txt?JSON.parse(txt):null}catch{d=txt}if(!r.ok)throw new Error(d?.message||d||('Request failed: '+r.status));return d}
function idOf(x){return x?.id??x?.farmerId??x?.officerId}
function nameOf(x){return x?.name??x?.fullName??'User #'+idOf(x)}
function regionName(x){return x?.region?.name??x?.regionName??'Region not set'}
function unwrap(x){return Array.isArray(x)?x:(x?.content||x?.data||[])}
function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function msg(id,t,bad=false){const e=$(id);if(e){e.textContent=t;e.style.color=bad?'#ad3934':'#237a52'}}
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
async function basics(){for(const k of ['farmers','officers','regions'])try{state[k]=unwrap(await api('/api/'+k))}catch(e){state[k]=[]}}
function fill(id,arr,ph){const e=$(id);if(e)e.innerHTML='<option value="">'+ph+'</option>'+arr.map(x=>'<option value="'+esc(idOf(x))+'">'+esc(nameOf(x))+(regionName(x)!=='Region not set'?' — '+esc(regionName(x)):'')+'</option>').join('')}
const PortalUI={
async initLogin(){await basics();fill('farmerSelect',state.farmers,'Select an existing farmer');fill('officerSelect',state.officers,'Select an agricultural officer');const r=$('newFarmerRegion');if(r)r.innerHTML='<option value="">Select region</option>'+state.regions.map(x=>'<option value="'+idOf(x)+'">'+esc(nameOf(x))+'</option>').join('');document.querySelectorAll('.role-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.role-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('farmerLogin').classList.toggle('hidden',b.dataset.role!=='farmer');$('officerLogin').classList.toggle('hidden',b.dataset.role!=='officer')});$('farmerLoginBtn').onclick=()=>{const f=state.farmers.find(x=>String(idOf(x))===String($('farmerSelect').value));if(!f)return msg('loginMessage','Select a farmer first.',true);sessionStorage.setItem('cropAdvisorUser',JSON.stringify({role:'farmer',user:f}));location.href='farmer.html'};$('officerLoginBtn').onclick=()=>{const o=state.officers.find(x=>String(idOf(x))===String($('officerSelect').value));if(!o)return msg('officerMessage','Select an officer first.',true);sessionStorage.setItem('cropAdvisorUser',JSON.stringify({role:'officer',user:o}));location.href='officer.html'};$('registerFarmerBtn').onclick=async()=>{const name=$('newFarmerName').value.trim(),phone=$('newFarmerPhone').value.trim(),regionId=$('newFarmerRegion').value;if(!name||!regionId)return msg('loginMessage','Name and region are required.',true);try{const f=await api('/api/farmers',{method:'POST',body:JSON.stringify({name,phone,regionId})});sessionStorage.setItem('cropAdvisorUser',JSON.stringify({role:'farmer',user:f}));location.href='farmer.html'}catch(e){msg('loginMessage',e.message,true)}}},
require(role){try{const x=JSON.parse(sessionStorage.getItem('cropAdvisorUser'));if(!x||x.role!==role)throw 0;return x.user}catch{location.href='index.html';return null}},
logout(){sessionStorage.removeItem('cropAdvisorUser');location.href='index.html'},
showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('view-'+v)?.classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const l={home:'Dashboard',new:'New Disease Query',tickets:'My Tickets',queue:'Assigned Queue',escalated:'Escalations',profile:'Profile'};if($('pageTitle'))$('pageTitle').textContent=l[v];if(v==='tickets')renderFarmer();if(v==='queue')renderOfficer();if(v==='escalated')renderEscalated()},
async initFarmer(){const f=this.require('farmer');if(!f)return;state.farmer=f;setText('farmerName',nameOf(f));setText('heroName',nameOf(f).split(' ')[0]);setText('farmerRegion',regionName(f));setText('farmerAvatar',nameOf(f)[0].toUpperCase());setText('profileAvatar',nameOf(f)[0].toUpperCase());setText('profileName',nameOf(f));setText('profilePhone',f.phone||'Phone not provided');setText('profileRegion',regionName(f));document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>this.showView(x.dataset.view));$('ticketForm').onsubmit=submitTicket;$('farmerSearch').oninput=renderFarmer;$('farmerStatus').onchange=renderFarmer;await loadFarmer()},
async initOfficer(){const o=this.require('officer');if(!o)return;state.officer=o;setText('officerName',nameOf(o));setText('officerRegion',regionName(o));setText('officerAvatar',nameOf(o)[0].toUpperCase());setText('profileAvatar',nameOf(o)[0].toUpperCase());setText('profileName',nameOf(o));setText('profileCode','Officer ID: '+idOf(o));setText('profileRegion',regionName(o));document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>this.showView(x.dataset.view));$('officerSearch').oninput=renderOfficer;$('officerStatus').onchange=renderOfficer;await loadOfficer()},
closeModal(){$('recommendModal')?.classList.remove('open');state.activeTicket=null},
openRecommendation(id){state.activeTicket=state.tickets.find(t=>String(idOf(t))===String(id));if(!state.activeTicket)return;setText('modalTitle','Recommendation for '+(state.activeTicket.cropName||'ticket'));setText('modalMeta','Ticket #'+idOf(state.activeTicket)+' · '+(state.activeTicket.farmer?.name||'Farmer'));$('recommendationText').value=state.activeTicket.recommendation||'';$('modalMessage').textContent='';$('recommendModal').classList.add('open')},
async saveRecommendation(){if(!state.activeTicket)return;const text=$('recommendationText').value.trim();if(!text)return msg('modalMessage','Recommendation cannot be empty.',true);try{await api('/api/tickets/'+idOf(state.activeTicket)+'/recommendation',{method:'POST',body:JSON.stringify({recommendation:text,officerId:idOf(state.officer)})});this.closeModal();toast('Recommendation saved');await loadOfficer()}catch(e){msg('modalMessage',e.message,true)}},
async closeTicket(id){try{await api('/api/tickets/'+id+'/close',{method:'PUT',body:JSON.stringify({officerId:idOf(state.officer)})});toast('Ticket closed');await loadOfficer()}catch(e){toast('Close failed: '+e.message)}},
async reopenTicket(id){try{await api('/api/tickets/'+id+'/reopen',{method:'PUT',body:JSON.stringify({farmerId:idOf(state.farmer)})});toast('Ticket reopened');await loadFarmer()}catch(e){toast('Reopen failed: '+e.message)}}
};
function setText(id,t){const e=$(id);if(e)e.textContent=t}
async function submitTicket(ev){ev.preventDefault();try{await api('/api/tickets',{method:'POST',body:JSON.stringify({farmerId:idOf(state.farmer),cropName:$('cropName').value.trim(),symptoms:$('symptoms').value.trim(),photoReference:$('photoReference').value.trim()})});$('ticketForm').reset();msg('ticketMessage','Ticket submitted successfully.');toast('Disease query submitted');await loadFarmer()}catch(e){msg('ticketMessage',e.message,true)}}
async function loadFarmer(){try{const all=unwrap(await api('/api/tickets'));state.tickets=all.filter(t=>String(t.farmer?.id??t.farmerId)===String(idOf(state.farmer)));stats();renderRecent();renderFarmer()}catch(e){toast('Could not load tickets: '+e.message)}}
async function loadOfficer(){try{const all=unwrap(await api('/api/officers/'+idOf(state.officer)+'/tickets'));state.tickets=all;stats();renderPriority();renderOfficer();renderEscalated()}catch(e){toast('Could not load assigned tickets: '+e.message)}}
function stats(){const c=s=>state.tickets.filter(t=>String(t.status).toUpperCase()===s).length;['Total','Pending','Escalated','Closed'].forEach((x,i)=>setText('stat'+x,i?c(x.toUpperCase()):state.tickets.length))}
function card(t,role){const s=String(t.status||'PENDING').toUpperCase(),id=idOf(t),crop=t.cropName||t.subject||'Crop',farmer=t.farmer?.name||t.farmerName||'Farmer';let a='';if(role==='farmer'&&s==='CLOSED')a='<button class="btn secondary" onclick="PortalUI.reopenTicket('+id+')">Reopen</button>';if(role==='officer'&&s!=='CLOSED')a='<button class="btn secondary" onclick="PortalUI.openRecommendation('+id+')">'+(t.recommendation?'Edit recommendation':'Add recommendation')+'</button><button class="btn primary" onclick="PortalUI.closeTicket('+id+')">Close</button>';return '<article class="ticket-card"><div class="ticket-top"><span class="ticket-id">TICKET #'+esc(id)+'</span><span class="badge '+s.toLowerCase()+'">'+esc(s)+'</span></div><h3>'+esc(crop)+'</h3><div class="symptoms">'+esc(t.symptoms||t.description||'No symptoms recorded')+'</div><div class="meta-grid"><div><small>Farmer</small><b>'+esc(farmer)+'</b></div><div><small>Officer</small><b>'+esc(t.officer?.name||'Assigned')+'</b></div></div>'+(t.recommendation?'<div class="recommendation"><b>Recommendation:</b> '+esc(t.recommendation)+'</div>':'')+(a?'<div class="ticket-actions">'+a+'</div>':'')+'</article>'}
function renderFarmer(){const e=$('farmerTickets');if(!e)return;const q=($('farmerSearch').value||'').toLowerCase(),s=$('farmerStatus').value,ts=state.tickets.filter(t=>(s==='ALL'||String(t.status).toUpperCase()===s)&&(!q||JSON.stringify(t).toLowerCase().includes(q)));e.innerHTML=ts.length?ts.map(t=>card(t,'farmer')).join(''):'<div class="panel"><b>No matching tickets</b><p class="hint">Submit a new query or change the filter.</p></div>'}
function renderOfficer(){const e=$('officerTickets');if(!e)return;const q=($('officerSearch').value||'').toLowerCase(),s=$('officerStatus').value,ts=state.tickets.filter(t=>(s==='ALL'||String(t.status).toUpperCase()===s)&&(!q||JSON.stringify(t).toLowerCase().includes(q)));e.innerHTML=ts.length?ts.map(t=>card(t,'officer')).join(''):'<div class="panel"><b>No assigned tickets</b><p class="hint">New regional tickets will appear here.</p></div>'}
function renderRecent(){const e=$('recentTickets');if(!e)return;e.innerHTML=state.tickets.slice(0,4).map(t=>'<div class="list-row"><div><b>'+esc(t.cropName||t.subject||'Crop')+'</b><small>#'+idOf(t)+' · '+esc(t.symptoms||'')+'</small></div><span class="badge '+String(t.status).toLowerCase()+'">'+esc(t.status)+'</span></div>').join('')||'<div class="hint">No tickets yet.</div>'}
function renderPriority(){const e=$('priorityTickets');if(!e)return;const ts=state.tickets.filter(t=>['PENDING','ESCALATED'].includes(String(t.status).toUpperCase())).slice(0,6);e.innerHTML=ts.length?ts.map(t=>card(t,'officer')).join(''):'<div class="panel"><b>Queue is clear</b></div>'}
function renderEscalated(){const e=$('escalatedTickets');if(!e)return;const ts=state.tickets.filter(t=>String(t.status).toUpperCase()==='ESCALATED');e.innerHTML=ts.length?ts.map(t=>card(t,'officer')).join(''):'<div class="panel"><b>No escalated cases</b></div>'}