package com.cropadvisor;
import jakarta.persistence.*; import org.springframework.boot.*; import org.springframework.boot.autoconfigure.*; import org.springframework.data.jpa.repository.*; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@SpringBootApplication public class CropAdvisorApplication {
 public static void main(String[] a){SpringApplication.run(CropAdvisorApplication.class,a);}
 @Entity public static class Region{@Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; @Column(unique=true,nullable=false) public String name; public Region(){} public Region(String n){name=n;}}
 @Entity public static class Farmer{@Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; public String name,phone,email,crop; @ManyToOne public Region region; public Farmer(){} }
 @Entity public static class Officer{@Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; public String name,phone,email; @ManyToOne public Region region; public Officer(){} }
 @Entity public static class Ticket{@Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; public String subject,description,status,priority,advice; public LocalDateTime createdAt,updatedAt,closedAt; @ManyToOne public Farmer farmer; @ManyToOne public Officer officer; @PrePersist void p(){createdAt=updatedAt=LocalDateTime.now();if(status==null)status="OPEN";} @PreUpdate void u(){updatedAt=LocalDateTime.now();}}
 public interface Regions extends JpaRepository<Region,Long>{Optional<Region> findByNameIgnoreCase(String n);}
 public interface Farmers extends JpaRepository<Farmer,Long>{}
 public interface Officers extends JpaRepository<Officer,Long>{Optional<Officer> findFirstByRegionId(Long id);}
 public interface Tickets extends JpaRepository<Ticket,Long>{List<Ticket> findByFarmerIdOrderByCreatedAtDesc(Long id);}
 @RestController @RequestMapping("/api") @CrossOrigin(origins="*") public static class Api {final Regions r;final Farmers f;final Officers o;final Tickets t; Api(Regions r,Farmers f,Officers o,Tickets t){this.r=r;this.f=f;this.o=o;this.t=t;} @GetMapping("/regions") public List<Region> regions(){return r.findAll();} @GetMapping("/farmers") public List<Farmer> farmers(){return f.findAll();} @GetMapping("/officers") public List<Officer> officers(){return o.findAll();} @GetMapping("/tickets") public List<Ticket> tickets(){return t.findAll();} @GetMapping("/farmers/{id}/tickets") public List<Ticket> byFarmer(@PathVariable Long id){return t.findByFarmerIdOrderByCreatedAtDesc(id);} @PostMapping("/tickets") public Ticket create(@RequestBody Ticket x){x.farmer=f.findById(x.farmer.id).orElseThrow();if(x.farmer.region!=null)o.findFirstByRegionId(x.farmer.region.id).ifPresent(v->x.officer=v);if(x.status==null)x.status="OPEN";if(x.priority==null)x.priority="NORMAL";return t.save(x);} @PutMapping("/tickets/{id}/status") public Ticket status(@PathVariable Long id,@RequestParam String value){Ticket x=t.findById(id).orElseThrow();x.status=value.toUpperCase();if(x.status.equals("CLOSED"))x.closedAt=LocalDateTime.now();return t.save(x);}}
}